const images = [

  

  //language Translator
  {
    Name: "Language Translator",
    navigate: "/language-translator",
    type: "language",
    maintype: "language",
  },


  // PPTX
  {
    Name: "PPT to PDF",
    navigate: "/ppt-to-pdf",
    extension: "pdf",
    type: "ppt",
    maintype: "ppt",
  },
  {
    Name: "PPT to PNG",
    navigate: "/ppt-to-png",
    extension: "png",
    type: "ppt",
    maintype: "ppt",
  },

  // Image Tools

  // Image Editor Tool
  {
    Name: "Image Cropper",
    navigate: "/image-cropper",
    type: "imageeditor",
    maintype: "imageeditor",
  },
  {
    Name: "Image Filters",
    navigate: "/image-filters",
    type: "imageeditor",
    maintype: "imageeditor",
  },
  {
    Name: "Image Resize",
    navigate: "/image-resize",
    type: "imageeditor",
    maintype: "imageeditor",
  },
  {
    Name: "Image Compressor",
    navigate: "/image-compressor",
    type: "imageeditor",
    maintype: "imageeditor",
  },
  {
    Name: "Image Color Extractor",
    navigate: "/image-color-extractor",
    type: "imageeditor",
    maintype: "imageeditor",
  },
  {
    Name: "Image Watermark",
    navigate: "/image-watermark",
    type: "imageeditor",
    maintype: "imageeditor",
  },
  {
    Name: "Get Your Color",
    navigate: "/get-your-color",
    type: "imageeditor",
    maintype: "imageeditor",
  },
  {
    Name: "Base64 To Image Convertor",
    navigate: "/base64-to-image-convertor",
    type: "imageeditor",
    maintype: "imageeditor",
  },
  {
    Name: "Image To Base64 Convertor",
    navigate: "/image-to-base64-convertor",
    type: "imageeditor",
    maintype: "imageeditor",
  },
  {
    Name: "Text To Image Convertor",
    navigate: "/text-to-image-convertor",
    type: "imageeditor",
    maintype: "imageeditor",
  },
  {
    Name: "Combine Image",
    navigate: "/combine-image",
    type: "imageeditor",
    maintype: "imageeditor",
  },
  {
    Name: "Meme Generator",
    navigate: "/meme-generator",
    type: "imageeditor",
    maintype: "imageeditor",
  },

  //  Calculator Tools
  {
    Name: "Age Calculator",
    navigate: "/age-calculator",
    type: "calculator",
    maintype: "calculator",
  },
  {
    Name: "BMI Calculator",
    navigate: "/bmi-calculator",
    type: "calculator",
    maintype: "calculator",
  },
  {
    Name: "Log(Logarithm) Calculator",
    navigate: "/log(logarithm)-calculator",
    type: "calculator",
    maintype: "calculator",
  },
  {
    Name: "GST Calculator",
    navigate: "/gst-calculator",
    type: "calculator",
    maintype: "calculator",
  },
  // FileIncomeTaxCalc
  {
    Name: "Loan Calculator",
    navigate: "/loan-calculator",
    type: "calculator",
    maintype: "calculator",
  },
  {
    Name: "% Calculator",
    navigate: "/percentage-calculator",
    type: "calculator",
    maintype: "calculator",
  },
  {
    Name: "Salary Calculator",
    navigate: "/salary-calculator",
    type: "calculator",
    maintype: "calculator",
  },
  {
    Name: "Timesheet Calculator",
    navigate: "/timesheet-calculator",
    type: "calculator",
    maintype: "calculator",
  },
  // <FileUploadBoxCalc/>
  {
    Name: "CGPA/CPI To Percentage Calculator",
    navigate: "/cpi-cgpa-to-percentage-calculator",
    type: "calculator",
    maintype: "calculator",
  },
  {
    Name: "Mortgage Calculator",
    navigate: "/mortgage-calculator",
    type: "calculator",
    maintype: "calculator",
  },
  {
    Name: "Saas Product Calculator",
    navigate: "/saas-product-calculator",
    type: "calculator",
    maintype: "calculator",
  },

  // TEXT TOOLS
  {
    Name: "Word Counter",
    navigate: "/word-counter",
    type: "texttools",
    maintype: "texttools",
  },
  {
    Name: "MD5 Generator",
    navigate: "/md5-generator",
    type: "texttools",
    maintype: "texttools",
  },
  {
    Name: "Uppercase to Lowercase",
    navigate: "/uppercase-to-lowercase",
    type: "texttools",
    maintype: "texttools",
  },
  {
    Name: "Lowercase to Uppercase",
    navigate: "/lowercase-to-uppercase",
    type: "texttools",
    maintype: "texttools",
  },
  {
    Name: "Combine the word",
    navigate: "/combine-the-word",
    type: "texttools",
    maintype: "texttools",
  },
  {
    Name: "Text Reverser",
    navigate: "/text-reverser",
    type: "texttools",
    maintype: "texttools",
  },

  {
    Name: "Split Text",
    navigate: "/split-text",
    type: "texttools",
    maintype: "texttools",
  },
  {
    Name: "Truncate Text",
    navigate: "/truncate-text",
    type: "texttools",
    maintype: "texttools",
  },
  {
    Name: "URL Encode",
    navigate: "/url-encode",
    type: "texttools",
    maintype: "texttools",
  },
  {
    Name: "URL Decode",
    navigate: "/url-decode",
    type: "texttools",
    maintype: "texttools",
  },
  {
    Name: "Remove white spaces",
    navigate: "/remove-all-white-spaces",
    type: "texttools",
    maintype: "texttools",
  },
  {
    Name: "Text Compare",
    navigate: "/text-compare",
    type: "texttools",
    maintype: "texttools",
  },
  {
    Name: "Fancy Font",
    navigate: "/fancy-font",
    type: "texttools",
    maintype: "texttools",
  },

  {
    Name: "Text to Speech",
    navigate: "/text-to-speech",
    type: "texttools",
    maintype: "texttools",
  },
  {
    Name: "Speech to Text",
    navigate: "/speech-to-text",
    type: "texttools",
    maintype: "texttools",
  },

  //Text Case Inverter
  {
    Name: "Text Case Inverter",
    navigate: "/text-case-inverter",
    type: "texttools",
    maintype: "texttools",
  },
  //Text To PDF
  {
    Name: "Text To PDF",
    navigate: "/text-to-pdf",
    type: "texttools",
    maintype: "texttools",
  },

  // Unit Convertor tools
  {
    Name: "Length",
    navigate: "/length-convertor",
    type: "unit",
    dataType: "convert",
    maintype: "unit",
    UnitArray: [
      "mm (milimeter)",
      "cm (centimeter)",
      "m (meter)",
      "in (inch)",
      "ft (foot)",
      "mi (mile)",
    ],
  },
  {
    Name: "Temprature",
    navigate: "/temprature-convertor",
    type: "unit",
    dataType: "convert",
    maintype: "unit",
    UnitArray: ["C (celsius)", "F (fahrenheit)", "K (kelvin)", "R (rankine)"],
  },
  {
    Name: "Area",
    navigate: "/area-convertor",
    type: "unit",
    dataType: "convert",
    maintype: "unit",
    UnitArray: [
      "mm2 (square millimetre)",
      "cm2 (square centimeter)",
      "m2 (square meter)",
      "ha (hectare)",
      "km2 (square kilometer)",
      "ft2 (square foot)",
      "ac (acre)",
      "mi2 (square mile)",
    ],
  },
  {
    Name: "Pressure",
    navigate: "/pressure-convertor",
    type: "unit",
    dataType: "convert",
    maintype: "unit",
    UnitArray: [
      "Pa (pascal)",
      "hPa (hectopascal)",
      "kPa (kilopascal)",
      "MPa (megapascal)",
      "bar ",
      "torr ",
      "psi (pound per square inch)",
      "ksi (kilopounds per square inch)",
    ],
  },
  {
    Name: "Weight",
    navigate: "/weight-convertor",
    type: "unit",
    dataType: "convert",
    maintype: "unit",
    UnitArray: [
      "mcg (microgram)",
      "mg (miligram)",
      "g (gram)",
      "kg (kilogram)",
      "oz (ounce)",
      "lb ",
      "mt (megatonne)",
      "t (tonne)",
    ],
  },
  {
    Name: "Volume",
    navigate: "/volume-convertor",
    type: "unit",
    dataType: "convert",
    maintype: "unit",
    UnitArray: [
      "mm3 (cubic milimeter)",
      "cm3 (cubic centimeter)",
      "ml (mililiter)",
      "l (liter)",
      "kl (kiloliter)",
      "m3 (cubic meter)",
      "km3 (cubic kilometer)",
      "tsp (teaspoon)",
      "Tbs (tablespoons)",
      "in3 (cubic inch)",
      "cup",
      "pnt (pints)",
      "qt",
      "gal (quarter gallon)",
      "ft3 (cubic foot)",
      "yd3 (cubic yard)",
    ],
  },
  {
    Name: "Volume flow rate",
    navigate: "/volume-flow-rate-convertor",
    type: "unit",
    dataType: "convert",
    maintype: "unit",
    UnitArray: [
      "mm3/s (cubic millimeter per second)",
      "cm3/s (cubic centimetre per second)",
      "ml/s (millileater per second)",
      "l/s (liters per second)",
      "l/min (liters per minute)",
      "l/h (liters per hour)",
      "m3/s (cubic meter per second)",
      "m3/min (cubic meter per minute)",
      "m3/h (cubic meter per hour)",
      "km3/s (cubic kilometer per hour)",
      "tsp/s (teaspoon per second)",
      "in3/s (cubic inch per second)",
      "in3/min (cubic inch per minute)",
      "in3/h (cubic inch per hour)",
      "fl-oz/s (fluid ounce per second)",
      "fl-oz/min (fluid ounce per minute)",
      "fl-oz/h (fluid ounce per hour)",
      "cup/s (Flow cups per second)",
      "gal/s (gallons per second)",
      "gal/min (gallons per minute)",
      "gal/h (gallons per hour)",
      "ft3/s (cubic feet per second)",
      "ft3/min (cubic feet per minute)",
      "ft3/h (cubic feet per hour)",
      "yd3/s (cubic yard per second)",
      "yd3/min (cubic yard per minute)",
      "yd3/h' (cubic yard per hour)",
    ],
  },
  {
    Name: "Time",
    navigate: "/time-convertor",
    type: "unit",
    dataType: "convert",
    maintype: "unit",
    UnitArray: [
      "ns (nanosecond)",
      "ms (milisecond)",
      "s (second)",
      "min (minute)",
      "h (hour)",
      "d (day)",
      "week",
      "month",
      "year",
    ],
  },
  {
    Name: "Frequency",
    navigate: "/frequency-convertor",
    type: "unit",
    dataType: "convert",
    maintype: "unit",
    UnitArray: [
      "Hz (hertz)",
      "mHz (milihertz)",
      "kHz (kilohertz)",
      "MHz (megahertz)",
      "GHz (gigahertz)",
      "THz (terahertz )",
      "rpm (revolutions per minute)",
      "deg/s",
      "rad/s",
    ],
  },
  {
    Name: "Speed",
    navigate: "/speed-convertor",
    type: "unit",
    dataType: "convert",
    maintype: "unit",
    UnitArray: [
      "m/s (meter per second)",
      "km/h (kilometer per hour)",
      "m/h (meter per hour)",
      "knot",
      "ft/s (feet per second)",
    ],
  },
  {
    Name: "Pace",
    navigate: "/pace-convertor",
    type: "unit",
    dataType: "convert",
    maintype: "unit",
    UnitArray: [
      "s/m (second per meter)",
      "min/km (minute per kilometer)",
      "s/ft (second per feet)",
      "min/km (minute per kilometer)",
    ],
  },
  {
    Name: "Illuminance",
    navigate: "/illuminance-convertor",
    type: "unit",
    dataType: "convert",
    maintype: "unit",
    UnitArray: ["lx", "ft-cd (footcandle)"],
  },
  {
    Name: "Digital",
    navigate: "/digital-convertor",
    type: "unit",
    dataType: "convert",
    maintype: "unit",
    UnitArray: [
      "b (bit)",
      "Kb (kilobit)",
      "Mb (megabit)",
      "Gb (gigabit)",
      "Tb (terabit)",
      "B (byte)",
      "KB (kilobyte)",
      "MB (megabyte)",
      "GB (gigabyte)",
      "TB (terabyte)",
    ],
  },
  {
    Name: "Angle",
    navigate: "/angle-convertor",
    type: "unit",
    dataType: "convert",
    maintype: "unit",
    UnitArray: ["deg", "rad", "grad", "arcmin", "arcsec"],
  },
  {
    Name: "Energy",
    navigate: "/energy-convertor",
    type: "unit",
    dataType: "convert",
    maintype: "unit",
    UnitArray: [
      "Wh (watthour)",
      "mWh (milliwatthour)",
      "kWh (kilowatthour)",
      "MWh (megawatthour)",
      "GWh (gigawatthour)",
      "J (joule)",
      "kJ (kilojoule)",
    ],
  },
  {
    Name: "Parts-Per",
    navigate: "/Parts-per",
    type: "unit",
    dataType: "convert",
    maintype: "unit",
    UnitArray: [
      "ppm (part per million)",
      "ppb (part per billion)",
      "ppt (part per trillion )",
      "ppq (part per quadrillion)",
    ],
  },
  {
    Name: "Voltage",
    navigate: "/voltage",
    type: "unit",
    dataType: "convert",
    maintype: "unit",
    UnitArray: ["V (voltage)", "mV (millivolt)", "kV (kilovolt)"],
  },
  {
    Name: "Apparent Power",
    navigate: "/apparent-power",
    type: "unit",
    dataType: "convert",
    maintype: "unit",
    UnitArray: [
      "VA (volt-ampere)",
      "mVA (milli volt-ampere)",
      "kVA (kilo volt-ampere)",
      "MVA (mega volt-ampere)",
      "GVA (giga volt-ampere)",
    ],
  },
  {
    Name: "Reactive Power",
    navigate: "/reactive-power",
    type: "unit",
    dataType: "convert",
    maintype: "unit",
    UnitArray: [
      "VAR (volt-amps reactive)",
      "kVAR (kilo volt-amps reactive)",
      "mVAR (milli volt-amps reactive)",
      "MVAR (mega volt-amps reactive)",
      "GVAR (giga volt-amps reactive)",
    ],
  },
  {
    Name: "Density",
    navigate: "/density",
    type: "unit",
    dataType: "convertpro",
    maintype: "unit",
    UnitArray: [
      "grainsGallonUK",
      "grainsGallonUS",
      "gramsCubicCentimeters",
      "gramsLiter",
      "gramsMilliliters",
      "kilogramsCubicMeters",
      "kilogramsLiter",
      "megagramsCubicMeter",
      "milligramsMilliliter",
      "milligramsLiter",
      "ouncesCubicInch",
      "ouncesGallonUK",
      "ouncesGallonUS",
      "poundsCubicInch",
      "poundsCubicFoot",
      "poundsGallonUK",
      "poundsGallonUS",
      "slugsCubicFoot",
      "tonnesCubicMeter",
      "tonsUKCubicYard",
      "tonsUSCubicYard",
    ],
  },
  {
    Name: "Energy Extra Unit",
    navigate: "/energy-extra-unit",
    type: "unit",
    dataType: "convertpro",
    maintype: "unit",
    UnitArray: [
      "btuTh",
      "btuMean",
      "caloriesIT",
      "caloriesTh",
      "caloriesMean",
      "calories15C",
      "calories20C",
      "caloriesFood",
      "centigradeHeatUnits",
      "dutchNaturalGas",
      "electronVolts",
      "ergs",
      "footPoundForce",
      "footPoundals",
      "gasolineL",
      "gigajoules",
      "horsepowerHours",
      "inchPoundForce",
      "joules",
      "kilocaloriesIT",
      "kilocaloriesTh",
      "kilogramForceMeters",
      "kilojoules",
      "kilowattHours",
      "megajoules",
      "newtonMeters",
      "petajoules",
      "terajoules",
      "therms",
      "wattSeconds",
      "wattHours",
    ],
  },
  {
    Name: "Force",
    navigate: "/force",
    type: "unit",
    dataType: "convertpro",
    maintype: "unit",
    UnitArray: [
      "dynes",
      "kilogramsForce",
      "kilonewtons",
      "kips",
      "meganewtons",
      "newtons",
      "poundsForce",
      "poundals",
      "sthane",
      "tonnesForce",
      "tonsForceUK",
      "tonsForceUS",
    ],
  },
  {
    Name: "Power",
    navigate: "/power",
    type: "unit",
    dataType: "convertpro",
    maintype: "unit",
    UnitArray: [
      "BtuHour",
      "BtuMinute",
      "BtuSecond",
      "caloriesThHour",
      "caloriesThMinute",
      "caloriesThSecond",
      "footPoundsForceMinute",
      "footPoundsForceSecond",
      "gigawatts",
      "horsepowersElectric",
      "horsepowersInternational",
      "horsepowersWater",
      "horsepowersMetric",
      "watts",
      "joulesHour",
      "joulesMinute",
      "joulesSecond",
      "kilocaloriesThHour",
      "kilocaloriesThMinute",
      "kilogramForceMetersHour",
      "kilogramForceMetersMinute",
      "kilowatts",
      "megawatts",
      "terawatts",
      "tonOfRefrigeration",
      "petawatts",
    ],
  },

  // Binary Convertor tools
  {
    Name: "Text to Binary",
    navigate: "/text-to-binary",
    placeholder: "Enter your text here...",
    type: "binary",
    maintype: "binary",
  },
  {
    Name: "Binary to Text",
    navigate: "/binary-to-text",
    placeholder: "Type only number 0 and 1 ,Ex. -100101 101001...",
    type: "binary",
    maintype: "binary",
  },
  {
    Name: "Binary to Hex",
    navigate: "/binary-to-hex",
    placeholder: "Type only number 0 and 1 ,Ex. -100101 101001...",
    type: "binary",
    maintype: "binary",
  },
  {
    Name: "Hex to Binary",
    navigate: "/hex-to-binary",
    placeholder: "Enter proper hexadecimal value here...",
    type: "binary",
    maintype: "binary",
  },
  {
    Name: "Binary to Ascii",
    navigate: "/binary-to-ascii",
    placeholder: "Type only number 0 and 1 ,Ex. -100101 101001...",
    type: "binary",
    maintype: "binary",
  },
  {
    Name: "Ascii to Binary",
    navigate: "/ascii-to-binary",
    placeholder: "Type only number 0 and 1 ,Ex. -64",
    type: "binary",
    maintype: "binary",
  },
  {
    Name: "Binary to Decimal",
    navigate: "/binary-to-decimal",
    placeholder: "Type only number 0 and 1 ,Ex. -100101 101001...",
    type: "binary",
    maintype: "binary",
  },
  {
    Name: "Decimal to Binary",
    navigate: "/decimal-to-binary",
    placeholder: "Enter proper decimal value here...",
    type: "binary",
    maintype: "binary",
  },
  {
    Name: "Text to Ascii",
    navigate: "/text-to-ascii",
    placeholder: "Enter your text here...",
    type: "binary",
    maintype: "binary",
  },
  {
    Name: "Decimal to Hex",
    navigate: "/decimal-to-hex",
    placeholder: "Enter proper decimal value here...",
    type: "binary",
    maintype: "binary",
  },
  {
    Name: "Hex to Decimal",
    navigate: "/hex-to-decimal",
    placeholder: "Enter proper hexadecimal value here...",
    type: "binary",
    maintype: "binary",
  },
  {
    Name: "Text to Hex",
    navigate: "/text-to-hex",
    placeholder: "Enter your text here...",
    type: "binary",
    maintype: "binary",
  },
  {
    Name: "Hex to Text",
    navigate: "/hex-to-text",
    placeholder: "Enter proper hexadecimal value here...",
    type: "binary",
    maintype: "binary",
  },
  {
    Name: "Text to Decimal",
    navigate: "/text-to-decimal",
    placeholder: "Enter your text here...",
    type: "binary",
    maintype: "binary",
  },
  {
    Name: "Decimal to Text",
    navigate: "/decimal-to-text",
    placeholder: "Enter proper decimal value here...",
    type: "binary",
    maintype: "binary",
  },
  {
    Name: "Octal to Binary",
    navigate: "/octal-to-binary",
    placeholder: "Enter proper Octal value here...",
    type: "binary",
    maintype: "binary",
  },
  {
    Name: "Octal to Decimal",
    navigate: "/octal-to-decimal",
    placeholder: "Enter proper Octal value here...",
    type: "binary",
    maintype: "binary",
  },
  {
    Name: "Octal to Hex",
    navigate: "/octal-to-hex",
    placeholder: "Enter proper Octal value here...",
    type: "binary",
    maintype: "binary",
  },
  {
    Name: "Octal to Text",
    navigate: "/octal-to-text",
    placeholder: "Enter proper Octal value here...",
    type: "binary",
    maintype: "binary",
  },
  {
    Name: "Text to Octal",
    navigate: "/text-to-octal",
    placeholder: "Enter your text here...",
    type: "binary",
    maintype: "binary",
  },
  {
    Name: "Binary to Octal",
    navigate: "/binary-to-octal",
    placeholder: "Type only number 0 and 1 ,Ex. -100101 101001...",
    type: "binary",
    maintype: "binary",
  },
  {
    Name: "Decimal to Octal",
    navigate: "/decimal-to-octal",
    placeholder: "Enter proper decimal value here...",
    type: "binary",
    maintype: "binary",
  },
  {
    Name: "Hex to Octal",
    navigate: "/hex-to-octal",
    placeholder: "Enter proper hexadecimal value here...",
    type: "binary",
    maintype: "binary",
  },
  {
    Name: "Json to Text",
    navigate: "/json-to-text",
    placeholder: `Enter proper JSON value Ex. {"Happy Holidays":"⛄"}`,
    type: "binary",
    maintype: "binary",
  },
  {
    Name: "Ascii to Text",
    navigate: "/ascii-to-text",
    placeholder: "Type only number 0 and 1 ,Ex. -64",
    type: "binary",
    maintype: "binary",
  },

  // Development Tools
  {
    Name: "Meta Tag Generator",
    navigate: "/meta-tag-generator",
    type: "development",
    maintype: "development",
  },
  {
    Name: "Password Generator",
    navigate: "/password-generator",
    type: "development",
    maintype: "development",
  },
  {
    Name: "Password Strength Checker",
    navigate: "/password-strength-checker",
    type: "development",
    maintype: "development",
  },
  {
    Name: "QR Code Generator",
    navigate: "/qr-code-generator",
    type: "development",
    maintype: "development",
  },
  {
    Name: "QR Code Decoder",
    navigate: "/qr-code-decoder",
    type: "development",
    maintype: "development",
  },
  {
    Name: "Barcode Generator",
    navigate: "/barcode-generator",
    type: "development",
    maintype: "development",
  },
  {
    Name: "Lorem Ipsum Generator",
    navigate: "/lorem-ipsum-generator",
    type: "development",
    maintype: "development",
  },

  {
    Name: "Creditcard Number Checker",
    navigate: "/creditcard-number-checker",
    type: "development",
    maintype: "development",
  },
  {
    Name: "Favicon Generator",
    navigate: "/favicon-generator",
    type: "development",
    maintype: "development",
  },

  {
    Name: "Standup timer",
    navigate: "/standup-timer",
    type: "development",
    maintype: "development",
  },
  // {
  //   Name: "Countdown Timer",
  //   navigate: "/countdown-timer",
  //   type: "development",
  //   maintype: "development",
  // },
  {
    Name: "Pomodoro Timer",
    navigate: "/pomodoro",
    type: "development",
    maintype: "development",
  },

  {
    Name: "Tiny Url",
    navigate: "/tiny-url",
    type: "development",
    maintype: "development",
  },
  {
    Name: "Merge PDF",
    navigate: "/merge-pdf",
    type: "development",
    maintype: "development",
  },

  // Proxy Tools
  {
    Name: "What is My IP",
    navigate: "/check-ip-address",
    type: "proxy",
    maintype: "proxy",
  },
  {
    Name: "IP Location",
    navigate: "/find-ip-location",
    type: "proxy",
    maintype: "proxy",
  },
  // {
  //   Name: "Internet Speed Test",
  //   navigate: "/check-internet-speed-test",
  //   type: "proxy",
  //   maintype: "proxy",
  // },

  // Other Tools
  {
    Name: "Fake Address Generator",
    navigate: "/fake-address-generator",
    type: "other",
    maintype: "otherTools",
    conversion_type: "address",
  },
  {
    Name: "Fake Name Generator",
    navigate: "/fake-name-generator",
    type: "other",
    maintype: "otherTools",
    conversion_type: "name",
  },

  {
    Name: "Create Zip",
    navigate: "/create-zip",
    type: "other",
    maintype: "otherTools",
  },
  {
    Name: "Search Name",
    navigate: "/search-name",
    type: "other",
    maintype: "otherTools",
  },
  {
    Name: "Name Combiner",
    navigate: "/name-combiner",
    type: "other",
    maintype: "otherTools",
  },

  // TIME CONVERTOR TOOLS
  {
    Name: "Time Convertor",
    navigate: "/time-convert",
    type: "timeConvertor",
    maintype: "timeConvertor",
  },

  {
    Name: "Timestamp To Date Converter",
    navigate: "/timestamp-to-date",
    type: "timeConvertor",
    maintype: "timeConvertor",
  },

  {
    Name: "Date To Timestamp Converter",
    navigate: "/date-to-timestamp",
    type: "timeConvertor",
    maintype: "timeConvertor",
  },

  // Currency CONVERTOR TOOLS
  {
    Name: "Currency Convertor",
    navigate: "/currency-convertor",
    type: "currencyconvert",
    maintype: "currencyconvert",
  },

  // Contry TOOLS
  {
    Name: "Country Information",
    navigate: "/country-information",
    type: "countrytool",
    maintype: "countrytool",
  },

  // Social Media Tools
  {
    Name: "Instagram Post Generator",
    navigate: "/instagram-post-generator",
    type: "socialmedia",
    maintype: "socialmedia",
  },

  {
    Name: "Facebook Post Generator",
    navigate: "/facebook-post-generator",
    type: "socialmedia",
    maintype: "socialmedia",
  },

  {
    Name: "Tweet Post Generator",
    navigate: "/tweet-post-generator",
    type: "socialmedia",
    maintype: "socialmedia",
  },

  {
    Name: "Tweet to Image Converter",
    navigate: "/tweet-to-image",
    type: "socialmedia",
    maintype: "socialmedia",
  },

  {
    Name: "Youtube Post Generator",
    navigate: "/youtube-post-generator",
    type: "socialmedia",
    maintype: "socialmedia",
  },

  {
    Name: "Youtube Thumbnail",
    navigate: "/youtube-thumbnail",
    type: "socialmedia",
    maintype: "socialmedia",
  },

  // Online Number Tools
  {
    Name: "Generate Arithmetic Progression",
    navigate: "/generate-arithmetic-progression",
    type: "onlinenumber",
    maintype: "onlinenumber",
  },
  {
    Name: "Geomatric Series",
    navigate: "/geomatric-series",
    type: "onlinenumber",
    maintype: "onlinenumber",
  },
  {
    Name: "Generate Random Number",
    navigate: "/generate-random-number",
    type: "onlinenumber",
    maintype: "onlinenumber",
  },
  {
    Name: "Round The Number",
    navigate: "/round-the-number",
    type: "onlinenumber",
    maintype: "onlinenumber",
  },
  //Roman to number
  {
    Name: "Roman To Number",
    navigate: "/roman-to-number",
    type: "onlinenumber",
    maintype: "onlinenumber",
  },
  //number to roman
  {
    Name: "Number To Roman",
    navigate: "/number-to-roman",
    type: "onlinenumber",
    maintype: "onlinenumber",
  },
  {
    Name: "Prime Number Series",
    navigate: "/prime number-series",
    type: "onlinenumber",
    maintype: "onlinenumber",
  },
  {
    Name: "Fibonacci Number Series",
    navigate: "/fibonacci number-series",
    type: "onlinenumber",
    maintype: "onlinenumber",
  },
  //
  {
    Name: "Cube and Cube root",
    navigate: "/cube-cuberoot",
    type: "onlinenumber",
    maintype: "onlinenumber",
  },
  {
    Name: "Square and Square root",
    navigate: "/Square-Squareroot",
    type: "onlinenumber",
    maintype: "onlinenumber",
  },
  {
    Name: "Sum Of First N digits",
    navigate: "/Sum-Of-First-N-digits",
    type: "onlinenumber",
    maintype: "onlinenumber",
  },
  {
    Name: "Series Ordering of Numbers",
    navigate: "/Series-Ordering-of-Numbers",
    type: "onlinenumber",
    maintype: "onlinenumber",
  },
  {
    Name: "Prime factors of Number",
    navigate: "/Prime-factors-of-Number",
    type: "onlinenumber",
    maintype: "onlinenumber",
  },

  // Crypto Tools
  {
    Name: "ROT-13 Encode Data",
    navigate: "/rot-13-encode-data",
    type: "cryptotools",
    maintype: "cryptotools",
  },
  {
    Name: "ROT-13 Decode Data",
    navigate: "/rot-13-decode-data",
    type: "cryptotools",
    maintype: "cryptotools",
  },
  {
    Name: "ROT-47 Encode Data",
    navigate: "/rot-47-encode-data",
    type: "cryptotools",
    maintype: "cryptotools",
  },
  {
    Name: "ROT-47 Decode Data",
    navigate: "/rot-47-decode-data",
    type: "cryptotools",
    maintype: "cryptotools",
  },
  {
    Name: "SHA256 Hash Generator",
    navigate: "/sha256-hash-generator",
    type: "cryptotools",
    maintype: "cryptotools",
  },
  {
    Name: "SHA224 Hash Generator",
    navigate: "/sha224-hash-generator",
    type: "cryptotools",
    maintype: "cryptotools",
  },

  // Video download
  {
    Name: "FaceBook Video Downloader",
    navigate: "/fb-video-downloader",
    type: "videodownloader",
    maintype: "videodownloader",
  },
  {
    Name: "YouTube Downloader",
    navigate: "/yt-downloader",
    type: "videodownloader",
    maintype: "videodownloader",
  },
  {
    Name: "Twitter Downloader",
    navigate: "/twitter-video-downloader",
    type: "videodownloader",
    maintype: "videodownloader",
  },

  // coder tools
  {
    Name: "HTML Encode",
    navigate: "/html-encode",
    type: "codertools",
    maintype: "codertools",
  },
  {
    Name: "HTML Decode",
    navigate: "/html-decode",
    type: "codertools",
    maintype: "codertools",
  },
  // {
  //   Name: "Color Convertor",
  //   navigate: "/color-convertor",
  //   type: "codertools",
  //   maintype: "codertools",
  // },

  // Festival Post
  // {
  //   Name: "Festival Post",
  //   navigate: "/festival-post",
  //   type: "festivalpost",
  //   maintype: "festivalpost",
  // },
];

module.exports = {
  images,
};
